before_all do
  ENV["SLACK_URL"] ||= "https://hooks.slack.com/services/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"
end

def version_string(version_number, build_number)
  "#{version_number} (#{build_number})"
end

def change_log_since_last_tag
    # http://git-scm.com/docs/pretty-formats
    # <short hash> <commit title>
    return changelog_from_git_commits(pretty: '%h %s')
end

lane :before_integration do
  post_to_slack(progress:"[:train:------]", message: "Start building")
  # fetch the number of commits in the current branch
  build_number = number_of_commits

  # Set number of commits as the build number in the project's plist file before the bot actually start building the project.
  # This way, the generated archive will have an auto-incremented build number.
  set_info_plist_value(
    path: './TryCI/Info.plist',
    key: 'CFBundleVersion',
    value: "#{build_number}"
  )


  # Run `pod install`
  # cocoapods

  # Download provisioning profiles for the app and copy them to the correct folder.
  sigh(output_path: '/Library/Developer/XcodeServer/ProvisioningProfiles', skip_install: true)

  post_to_slack(progress:"[-:train:-----]", message: "Building new release version #{get_version_number()}")

end

lane :after_integration do
  plist_file = './TryCI/Info.plist'

  # Get the build and version numbers from the project's plist file
  build_number = get_info_plist_value(
    path: plist_file,
    key: 'CFBundleVersion',
  )
  version_number = get_info_plist_value(
    path: plist_file,
    key: 'CFBundleShortVersionString',
  )

  # Commit changes done in the plist file
  #  git_commit(
  # path: ["#{plist_file}"],
  # message: "Version bump to #{version_number} (#{build_number}) by CI Builder"
  #)

  post_to_slack(progress:"[--:train:----]", message: "Building for testiong")

  gym(scheme: "TryCI", clean: true, export_method:"ad-hoc", xcargs: "ARCHIVE=YES")

  post_to_slack(progress:"[---:train:---]", message: "Processing for testing with Crashlytics")
  
  crashlytics(
    api_token: ENV["CRASHLYTICS_TOKEN"],
    build_secret: ENV["CRASHLYTICS_SECRET"],
    notes: change_log_since_last_tag
              #    notifications: notify_testers
  )

  post_to_slack(progress:"[----:train:--]", message: "Building for AppStore")

  gym(scheme: "TryCI", clean: false, export_method:"app-store", xcargs: "ARCHIVE=YES")

  post_to_slack(progress:"[-----:train:-]", message: "Processing for testing with Testflight")
  
  change_log = "CHANGELOG TBD. Version: #{complete_version_number}"

  testflight(changelog: change_log)

  post_to_slack(progress:"[------:train:]", message: "Build is processed in ready to be tested #{get_version_number()} :tada:")

  # Keep committing and tagging actions after export & upload to prevent confirm the changes to the repo if something went wrong
  add_git_tag(
    tag: "beta/v#{version_number}_#{build_number}"
  )

#push_to_git_remote

#  push_git_tags

#  post_to_slack(progress:"[------:train:]", message: "Pushing version to remote")

end


private_lane :post_to_slack do |options|
  progress = options[:progress]
  message = options[:message]
  success = options[:success]
  last_slack_progress = progress
  slack(
    message: "#{progress} #{message}",
    slack_url: "https://hooks.slack.com/services/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",
    success: success,
    default_payloads: []
  )
end

error do |lane, exception|
  puts "Fail? with '#{lane}'  Excetption #{exception} "
  if lane == :release_new_version
    failure_message = last_slack_progress.gsub(":train:", ":boom:")
    post_to_slack(message: "#{failure_message} Broken! #{exception}", success: false)
  end
end
